version: '2.1'
services:
  ovation:
    image: rhel7-workstation-lx.swpc.noaa.gov/ovation:latest
    build: .
    tty: true
    volumes:
      #host:container
      - ./Output:/Output
    env_file:
      - ovation.env
    command: [ "python", "ovation_model.py" ]
    restart: "no"
